# deps_fetch.cmake — install dependencies via CMake FetchContent (fallback).
#
# For each dep, FetchContent_Declare(name GIT_REPOSITORY <git> GIT_TAG <git_tag|version>)
# is run, then we expose `${name}::${name}` as an ALIAS to the upstream
# target so subdirs can use the uniform `find_package(${name} CONFIG REQUIRED)
# + target_link_libraries(... ${name}::${name})` interface.
#
# Per-dep schema:
#   name           required
#   version        used as git tag if git_tag is absent
#   git            required for this backend
#   git_tag        optional override of version-as-tag
#   fetch_target   optional, name of the upstream library target to alias
#                  to ${name}::${name} (defaults to ${name})
#   features       silently ignored (vcpkg-only concept)

include(FetchContent)

set(BUILD_TESTING    OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES   OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS      OFF CACHE BOOL "" FORCE)
set(BUILD_TEST_APP   OFF CACHE BOOL "" FORCE)
set(EFSW_INSTALL     OFF CACHE BOOL "" FORCE)

# --- Backend interface: detect ----------------------------------------------
#
# FetchContent ships with CMake itself, so this backend is always available.
# Acts as the always-on fallback in deps.cmake's auto-detection chain.

function(_fetch_detect OUT_VAR)
    set(${OUT_VAR} TRUE PARENT_SCOPE)
endfunction()

function(deps_install_fetch DEPS_JSON)
    string(JSON _len LENGTH "${DEPS_JSON}" dependencies)
    math(EXPR _last "${_len} - 1")

    set(_redirect_root "${CMAKE_BINARY_DIR}/_fetch_configs")
    file(MAKE_DIRECTORY "${_redirect_root}")

    foreach(_i RANGE 0 ${_last})
        string(JSON _name    GET                        "${DEPS_JSON}" dependencies ${_i} name)
        string(JSON _ver     ERROR_VARIABLE _ev GET     "${DEPS_JSON}" dependencies ${_i} version)
        string(JSON _git     ERROR_VARIABLE _eg GET     "${DEPS_JSON}" dependencies ${_i} git)
        string(JSON _tag     ERROR_VARIABLE _et GET     "${DEPS_JSON}" dependencies ${_i} git_tag)
        string(JSON _ftarget ERROR_VARIABLE _eft GET    "${DEPS_JSON}" dependencies ${_i} fetch_target)

        if(_eg OR _git STREQUAL "")
            message(FATAL_ERROR
                "deps_install_fetch: '${_name}' needs a 'git' field in dependencies.json")
        endif()
        if(_et OR _tag STREQUAL "")
            set(_tag "${_ver}")
        endif()
        if(_eft OR _ftarget STREQUAL "")
            set(_ftarget "${_name}")
        endif()

        FetchContent_Declare(${_name}
            GIT_REPOSITORY "${_git}"
            GIT_TAG        "${_tag}"
            GIT_SHALLOW    TRUE
        )
        FetchContent_MakeAvailable(${_name})

        set(_alias "${_name}::${_name}")
        if(NOT TARGET ${_alias})
            if(TARGET ${_ftarget})
                add_library(${_alias} ALIAS ${_ftarget})
            else()
                message(FATAL_ERROR
                    "deps_install_fetch: ${_name}: upstream target '${_ftarget}' "
                    "not found after FetchContent. Set 'fetch_target' in dependencies.json.")
            endif()
        endif()

        set(_pkg_dir "${_redirect_root}/${_name}")
        file(MAKE_DIRECTORY "${_pkg_dir}")
        file(WRITE "${_pkg_dir}/${_name}Config.cmake"
"# Generated by deps_fetch.cmake — FetchContent redirect.
set(${_name}_FOUND TRUE)
")
        set(${_name}_DIR "${_pkg_dir}" CACHE PATH "" FORCE)
    endforeach()
endfunction()

list(APPEND _DEPS_BACKENDS "fetch")